version: '3.8'

services:
  vpn-proxy:
    build: .
    container_name: crypto-vpn-proxy
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - PROXY_TIMEOUT=30.0
      - MAX_RETRIES=3
      - RATE_LIMIT_DELAY=0.05
      - MAX_CONCURRENT_REQUESTS=10
    restart: unless-stopped
    # Resource limits for t2.micro
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - proxy-network

  nginx:
    image: nginx:alpine
    container_name: crypto-proxy-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - vpn-proxy
    restart: unless-stopped
    # Resource limits for t2.micro
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.1'
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge 